### ISSUE TITLE
UITableViewCell

### ISSUE THREAD

**Issue by markst** [marksands/MSTextView#2]
I'm using MSTextView inside a custom TableView cell for a small Twitter reader for my app.
Is this not a sensible idea to use this for a TableView?

The trouble I'm having is with TableView's reuseIdentifier. With a normal UITableView content is updated fine & only x amount & reuses them. 
However with MSTableView content doesn't seem to update - it reuses the same cell & text.

**Comment by marksands** [comment]
The purpose of MSTextView is to act and behave like a UITextView. TableView cells probably shouldn't render UITextViews in their layout. I'd stick with `cell.textLabel` and `cell.detailTextlabel`.

If you really want a highlighted label in your cell I'd suggest taking a look at NSAttributedString and this project https://github.com/AliSoftware/Ali-Cocoa-Classes/tree/master/OHAttributedLabel which will allow you to add a label in your TableView cells with this behavior.

**Comment by markst** [comment]
Well the main reason for using your code was to be able to load a custom UIWebView when a url is selected.
Can you give some advice as to achieving this without your class?

Thanks.

**Comment by marksands** [comment]
no, this is the recommended solution. But I wouldn't use this in a tableview cell. Mimic the official Twitter app. They display tweets in plain text in the table cells, and when you select a tweet it loads a new viewcontroller that displays the tweet, which is where you would use MSTextView.

Feel free to shoot me an email if you need help. Marksands07@gmail.com
