### ISSUE TITLE
Custom data detector types.

### ISSUE THREAD

**Issue by markst** [marksands/MSTextView#3]
At the moment the MSTextView detects http:// url's, well how about url's beginning with www. & should I want to add a custom detector for @twitterusername. I wasn't able to achieve this with the correct effect by adding to the linkRegex.
Thanks.

**Comment by marksands** [comment]
I added an experimental twitter branch to support `@usernames` and `#hashtags`. Pull from there: https://github.com/marksands/MSTextView/tree/twitter
