### ISSUE TITLE
App crash after adding MSTextView

### ISSUE THREAD

**Issue by md347** [marksands/MSTextView#4]
hi, i've added this to a detailView which i open from my UITableView. i can only open the detail view once, then when i close it and open again it crashes. if i add a UITextView without your code it runs fine, and has been for months. Any help would be appreciated. thanks

**Comment by marksands** [comment]
Can you provide me with a crash log so I can see what's going on?

**Comment by md347** [comment]
i've managed to fix it, i had to cancel these lines out in MSTextView.m:
//#define kFont [UIFont fontWithName:@"Helvetica" size:20]
//#define kBackgroundColor [UIColor clearColor]
//_font = kFont;
//_backgroundColor = kBackgroundColor.

**Comment by marksands** [comment]
You're using an old version. The kBackgroundColor isn't used anymore. You should pull the latest revision. :+1:

**Comment by md347** [comment]
i have got the latest one, but your twitter code isn't updated. thanks for your quick replies. quick question while i've got you here ;-), how do i set the MSTextView autosize.width?

**Comment by marksands** [comment]
blah, you're right. I'll update the twitter branch. Everything has been fixed in the main branch and it should work. I also added sizeToFit so it will auto fit to contents.
