### ISSUE TITLE
high cpu usage

### ISSUE THREAD

**Issue by lonre** [marksands/MSTextView#6]
http://d.pr/Ufly

**Comment by smit9612** [comment]
Hi,
I am also facing this issue, very high cpu usage after keep running MSTextview for 30sec..

**Comment by smit9612** [comment]
HI Mark,
Thanks for such a wonderful code. But I figure out - (void) layoutSubviews called several times tat increases memory. I looked into code this method prepare list of all weblinks using regex and load them in UIwebview. But this require to be done only when text get loaded in uiview.
But i cannot figure out why we required to write parsing code in layoutSubview method. As its help says You should override this method only if the autoresizing behaviors of the subviews do not offer the behavior you want.

**Comment by marksands** [comment]
Thanks guys. Sorry this took forever to finally get around to. I've replaced the old code with KVO, so the performance is much better. Let me know if there's any other issues!
